### ISSUE TITLE
HyperJaxb3 with Apache CXF issue: primary key creation from existing wsdl defined ids

### ISSUE THREAD

**Issue by SergiiShapoval** [highsource/hyperjaxb3-support#2] opened 2015-03-18 21:50 UTC
how we can avoid org.hibernate.AnnotationException: Unable to define/override @Id(s) on a subclass: integration.mindbody.Appointment

by configuring binding.xml? (initial discussion here - http://stackoverflow.com/questions/29125659/how-to-set-existing-id-as-primary-key-in-hyperjaxb3-cxf-project-code-generatio/29130869?noredirect=1#comment46490683_29130869)

@highsource

**Comment by highsource** [comment] 2015-03-18 22:50
I've just got a successful `mvn clean install`.

The problem is that your XPath `//s:element[@name='ID']` selects several `ID` elements, not just one. It actually selects all the `ID` elements in the schema.

This collides with complex types which inherit from other complex types (for instance, `MBObject`). Parent compex types already have ids (automatically generated) but your customization points to use the `ID` element as id anyway. This causes problems. Looks like HJ3 tries to generate a complex id (via `@IdClass`) but this fails in Hibernate.

The fix is not to override id property in subclasses. This can be achieved in two ways:

* Only customize `ID` elements in non-subclasses (in root classes).
* Customize parent classes with `hj:mapped-subclass`.

I've opted to the last solution and made `MBObject` and `ScheduleItem` mapped superclasses:

https://github.com/highsource/hyperjaxb3-support/blob/master/m/MindBody/src/main/wsdl/binding.xml#L60-L65

Thus classes like `Appointment` become (in JPA sense) root of the hierarchy and the id customization works correctly (mapped supperclasses do not have ids). So I get a successful build (database tests fail but don't break the build).

A further note: you generate the code under `src/main`, this is not a goof practice. Generate the code under `target/generated-sources/...` and also don't check it into SCM. I had a problem that I had to manually copy the `persistence.xml`. Consider using `build-helper-maven-plugin` to add these directories as source/resource directories, this is a cleaner way compared to code generation under `src/main`.

Hope this helps.

**Comment by SergiiShapoval** [comment] 2015-03-19 05:02
Yes, database entities generated successfully!  thank you very much, @highsource !))

I think, customizations of schema names (@Table(schema = "mindbody", name = "APPOINTMENT") instead of @Table(name = "APPOINTMENT")) and table entities names (add_arrival instead of addarrival) will be also useful

P. S.  build-helper-maven-plugin will be helpful, too!

**Comment by highsource** [comment] 2015-03-19 07:39
You can achieve this with customizations, check this test project:

https://github.com/highsource/hyperjaxb3/tree/master/ejb/tests/cu-one

Some docs:

http://confluence.highsource.org/display/HJ3/Customization+Guide

I'm closing this issue as we seem to have resolved the immediate cause.

**Closed by highsource** 2015-03-19 07:39 UTC

**Comment by SergiiShapoval** [comment] 2015-03-19 07:45
Yes, Thank you!
